/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedCharactersRouteImport } from './routes/_authenticated/characters'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedEpisodesIdRouteImport } from './routes/_authenticated/episodes.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharactersRoute = AuthenticatedCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEpisodesIdRoute = AuthenticatedEpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/video': typeof AuthenticatedVideoRoute
  '/episodes/$id': typeof AuthenticatedEpisodesIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/characters': typeof AuthenticatedCharactersRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/video': typeof AuthenticatedVideoRoute
  '/episodes/$id': typeof AuthenticatedEpisodesIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/support': typeof SupportRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/characters': typeof AuthenticatedCharactersRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
  '/_authenticated/episodes/$id': typeof AuthenticatedEpisodesIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/support'
    | '/account'
    | '/admin'
    | '/characters'
    | '/generate'
    | '/groups'
    | '/history'
    | '/studio'
    | '/usage'
    | '/video'
    | '/episodes/$id'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/support'
    | '/account'
    | '/admin'
    | '/characters'
    | '/generate'
    | '/groups'
    | '/history'
    | '/studio'
    | '/usage'
    | '/video'
    | '/episodes/$id'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/support'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/characters'
    | '/_authenticated/generate'
    | '/_authenticated/groups'
    | '/_authenticated/history'
    | '/_authenticated/studio'
    | '/_authenticated/usage'
    | '/_authenticated/video'
    | '/_authenticated/episodes/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters': {
      id: '/_authenticated/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AuthenticatedCharactersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/episodes/$id': {
      id: '/_authenticated/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/episodes/$id'
      preLoaderRoute: typeof AuthenticatedEpisodesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCharactersRoute: typeof AuthenticatedCharactersRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
  AuthenticatedEpisodesIdRoute: typeof AuthenticatedEpisodesIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCharactersRoute: AuthenticatedCharactersRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
  AuthenticatedEpisodesIdRoute: AuthenticatedEpisodesIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
